apiVersion: 1

datasources:
  - name: InfluxDB-IoT
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: industritech
      defaultBucket: iot_data
      tlsSkipVerify: true
    secureJsonData:
      token: mytoken123superlong
    editable: true
